name: Test My GitHub Action

on:
  pull_request:
    branches: [ main ]

jobs:
  test-my-action:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Symbols 📦
      uses: ./
      with:
        clientId: "${{ secrets.SYMBOL_UPLOAD_CLIENT_ID }}"
        clientSecret: "${{ secrets.SYMBOL_UPLOAD_CLIENT_SECRET }}"
        database: "${{ secrets.BUGSPLAT_DATABASE }}"
        application: "symbol-upload-test"
        version: "1.0"
        directory: "spec/support"
        files: "**/*.sym"
        node-version: '21'
